name: sanity-check-build

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild build -sdk iphonesimulator -scheme OktaTrack -destination "platform=iOS Simulator,name=iPhone 13 Pro"